### PR TITLE
Prepare 3.6

### PR DESCRIPTION
**Pull request by pmac**
Once this lands and we push the release to PyPI it should satisfy
the requests in #129.

### CODE REVIEW

**Comment by pmac** [comment]
I was going to do the release as well, but I don't have permissions on the repo.

@EnTeQuAk as soon as we merge and tag this it should be good to go AFAIK.

**Comment by EnTeQuAk** [comment]
Thanks a lot, I'll do the release either later today or on 23rd depending on how much free time my son gives me :see_no_evil:

**Comment by craiga** [comment]
@EnTeQuAk Any progress on getting 3.6 onto pypi?

**Comment by EnTeQuAk** [comment]
Apologies for the delay again, I didn't actually manage to startup my laptop during the holidays. I'll plan to issue the release today, ideally in the next few hours.

**Comment by craiga** [comment]
Thank you @EnTeQuAk !

**Pull request merged**
