### PR TITLE
Add support for Django 1.11 and Python 3.6

### PR DESCRIPTION
**Pull request by Flimm**
Django 1.11 has been released, so it's time to support it!

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I'll push this as a new release on Friday after looking through other open PRs and issues to see if something else might make a new release. Thanks again!

**Comment by Flimm** [comment]
Could a new version of django-csp be relased on PyPI? Personally, I think that supporting new Django and Python versions is enough of a change to merit a release. Currently, `pip check` will complain if you have Django 1.11 installed:

```
$ pip check
django-csp 3.2 has requirement Django<1.11,>=1.6, but you have Django 1.11.
```

Thanks!

**Comment by EnTeQuAk** [comment]
Just released version 3.3 on pypi. Thanks for the PR and the follow-up and sorry for the delay.

**Comment by Flimm** [comment]
Thanks @EnTeQuAk !

**Pull request merged**
