### PR TITLE
Django admin doesn't use inline JS anymore

### PR DESCRIPTION
**Pull request by graingert**
Once https://github.com/django/django/pull/5567/ lands Django admin will support django-csp out of the box

### CODE REVIEW

**Comment by graingert** [comment]
@jsocol  django/django#5567 just landed and will be released with Django 1.10

**Comment by jsocol** [comment]
I'm not maintaining django-csp anymore. 



--

**Comment by muffinresearch** [comment]
Doesn't look like there's anything to do on this from this end so closing.

**Comment by muffinresearch** [comment]
Oops my bad, going to leave this open.

**Comment by graingert** [comment]
@muffinresearch :(

**Comment by muffinresearch** [comment]
I wonder if we should just land this as-is because a user can choose to exclude the admin on their own.

**Comment by graingert** [comment]
@muffinresearch we could detect Django 1.10

**Comment by muffinresearch** [comment]
@graingert Yep, that sounds like a possible solution. We'd just need release notes to cover the eventuality where a user upgrades 1.10 in the future and has a modified admin or other things under the prefix which could start being blocked.

**Comment by graingert** [comment]
Hmm that's a bit of a pickle I don't really want this complexity in
security code. I think it's best to push a major version (breaking change)
and get people to manually add admin if they need it.

**Comment by muffinresearch** [comment]
Yep I'm inclined to agree.

**Comment by graingert** [comment]
@muffinresearch any chance of a merge?

**Comment by muffinresearch** [comment]
@graingert - yep will do shortly.

@EnTeQuAk, heads-up once this is merged - when the next release happens we'll need a major version + docs to say that if users are relying on `/admin` being excluded by default they'll need to update their config and add `/admin` to `CSP_EXCLUDE_URL_PREFIXES` explicitly.

**Pull request merged**
